mosip.id.auth.service-name=id-authentication-service
mosip.id.auth.version=1.0.0
mosip.id.auth.environment=local
mosip.id.auth.someConfig=hello-from-mosip-config
mosip.id.auth.forced-down=false

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:mosipdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
